<?php
$start = trim($_POST["start"]);
$end = trim($_POST["end"]);
    require("db_connect.php");
   $strSQL = "SELECT A_MEDICINE.MEDICINEID,A_MEDICINE.NAME,COUNT(A_MEDICINELIST.QUANTITY) AS COUNTQUANTIRY,A_MEDICINE.UNIT
FROM A_MEDICALHISTORY INNER JOIN A_MEDICINELIST ON A_MEDICALHISTORY.MEDICALHISTORYID=A_MEDICINELIST.MEDICALHISTORYID   INNER JOIN A_MEDICINE ON A_MEDICINELIST.MEDICINEID=A_MEDICINE.MEDICINEID  
WHERE TO_DATE (A_MEDICALHISTORY.DATEE, 'DD/MM/YYYY') BETWEEN TO_DATE ('$start','DD/MM/YYYY')  AND TO_DATE ('$end','DD/MM/YYYY')
GROUP BY  A_MEDICINE.MEDICINEID,A_MEDICINE.NAME,A_MEDICINE.UNIT";
    $objParse = oci_parse($objConnect, $strSQL);
    oci_execute($objParse);
    $nrows = oci_fetch_all($objParse, $objResult);
    echo $nrows;
    oci_close($objConnect);
