<?php
$start = trim($_POST["start"]);
$end = trim($_POST["end"]);
    require("db_connect.php");
    $strSQL = "SELECT * FROM (
SELECT A_MEDICALHISTORY.MEDICALHISTORYID,A_PATIENT.PATIENTID,A_PATIENT.TYPE,A_PATIENT.TNAME,A_PATIENT.LNAME,A_FACULTY.TNAME AS FACULTY,A_DISEASE.NAME AS DIS,TO_DATE(A_MEDICALHISTORY.DATEE, 'dd/mm/yyyy') AS DATEE,A_MEDICALHISTORY.TIME 
FROM A_MEDICALHISTORY INNER JOIN A_PATIENT ON A_MEDICALHISTORY.PATIENTID=A_PATIENT.PATIENTID  INNER JOIN A_FACULTY ON A_PATIENT.FACID=A_FACULTY.FACID INNER JOIN A_DISEASE ON A_DISEASE.DISEASEID=A_MEDICALHISTORY.DISEASEID
WHERE TO_DATE (A_MEDICALHISTORY.DATEE, 'DD/MM/YYYY') BETWEEN TO_DATE ('$start','DD/MM/YYYY')  AND TO_DATE ('$end','DD/MM/YYYY'))";
    $objParse = oci_parse($objConnect, $strSQL);
    oci_execute($objParse);
    $nrows = oci_fetch_all($objParse, $objResult);
    echo $nrows;
    oci_close($objConnect);
